# Malla parcial (triángulo): tres rutas entre tres sedes.

services:
  sede-1:
    image: lab-host:local
    hostname: sede-1
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      link-12:
        ipv4_address: 10.20.1.2
      link-13:
        ipv4_address: 10.20.3.2

  sede-2:
    image: lab-host:local
    hostname: sede-2
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      link-12:
        ipv4_address: 10.20.1.3
      link-23:
        ipv4_address: 10.20.2.2

  sede-3:
    image: lab-host:local
    hostname: sede-3
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      link-23:
        ipv4_address: 10.20.2.3
      link-13:
        ipv4_address: 10.20.3.3

networks:
  link-12:
    ipam:
      config:
        - subnet: 10.20.1.0/29
          gateway: 10.20.1.1
  link-23:
    ipam:
      config:
        - subnet: 10.20.2.0/29
          gateway: 10.20.2.1
  link-13:
    ipam:
      config:
        - subnet: 10.20.3.0/29
          gateway: 10.20.3.1
