interface=eth0
bind-interfaces
listen-address=192.168.52.2
no-resolv
no-poll
address=/intranet.lab/192.168.52.20
address=/web.intranet.lab/192.168.52.20
address=/www.intranet.lab/192.168.52.20
address=/alias.intranet.lab/192.168.52.30
