# Oficina central + dos sucursales unidas por una red WAN simulada (MPLS).

services:
  pc-oficina:
    image: lab-host:local
    hostname: pc-oficina
    cap_add:
      - NET_ADMIN
    networks:
      lan-oficina:
        ipv4_address: 192.168.10.10

  pc-sucursal-1:
    image: lab-host:local
    hostname: pc-sucursal-1
    cap_add:
      - NET_ADMIN
    networks:
      lan-sucursal-1:
        ipv4_address: 192.168.20.10

  pc-sucursal-2:
    image: lab-host:local
    hostname: pc-sucursal-2
    cap_add:
      - NET_ADMIN
    networks:
      lan-sucursal-2:
        ipv4_address: 192.168.30.10

  gw-oficina:
    image: lab-host:local
    hostname: gw-oficina
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      lan-oficina:
        ipv4_address: 192.168.10.254
      wan-mpls:
        ipv4_address: 10.255.0.11

  gw-sucursal-1:
    image: lab-host:local
    hostname: gw-sucursal-1
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      lan-sucursal-1:
        ipv4_address: 192.168.20.254
      wan-mpls:
        ipv4_address: 10.255.0.12

  gw-sucursal-2:
    image: lab-host:local
    hostname: gw-sucursal-2
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      lan-sucursal-2:
        ipv4_address: 192.168.30.254
      wan-mpls:
        ipv4_address: 10.255.0.13

networks:
  lan-oficina:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  lan-sucursal-1:
    ipam:
      config:
        - subnet: 192.168.20.0/24
  lan-sucursal-2:
    ipam:
      config:
        - subnet: 192.168.30.0/24
  wan-mpls:
    ipam:
      config:
        - subnet: 10.255.0.0/24
