services:
  servidor-sftp:
    image: lab-host:local
    hostname: servidor-sftp
    command: ["bash", "/opt/iniciar-sftp.sh"]
    volumes:
      - ./datos:/mnt/datos:ro
      - ./iniciar-sftp.sh:/opt/iniciar-sftp.sh:ro
    networks:
      lan-ftp:
        ipv4_address: 192.168.54.10

  cliente-ftp:
    image: lab-host:local
    hostname: cliente-ftp
    networks:
      lan-ftp:
        ipv4_address: 192.168.54.20

networks:
  lan-ftp:
    ipam:
      config:
        - subnet: 192.168.54.0/24
