# LAN interna + DMZ + internet simulada (M05).

services:
  pc-interno:
    image: lab-host:local
    hostname: pc-interno
    cap_add:
      - NET_ADMIN
    networks:
      lan-interna:
        ipv4_address: 10.70.1.10

  servidor-dmz:
    image: lab-host:local
    hostname: servidor-dmz
    command: >
      bash -c "python3 -m http.server 8080 --bind 0.0.0.0 & sleep infinity"
    networks:
      dmz:
        ipv4_address: 10.70.2.10

  atacante-internet:
    image: lab-host:local
    hostname: atacante-internet
    networks:
      internet:
        ipv4_address: 10.70.100.20

  firewall:
    image: lab-host:local
    hostname: firewall
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      lan-interna:
        ipv4_address: 10.70.1.254
      dmz:
        ipv4_address: 10.70.2.254
      internet:
        ipv4_address: 10.70.100.254

networks:
  lan-interna:
    ipam:
      config:
        - subnet: 10.70.1.0/24
  dmz:
    ipam:
      config:
        - subnet: 10.70.2.0/24
  internet:
    ipam:
      config:
        - subnet: 10.70.100.0/24
