# Dos "VLAN" = dos redes Docker + router (M08).

services:
  pc-ventas:
    image: lab-host:local
    hostname: pc-ventas
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "pc-rrhh:10.80.20.10"
    networks:
      vlan-ventas:
        ipv4_address: 10.80.10.10

  pc-rrhh:
    image: lab-host:local
    hostname: pc-rrhh
    cap_add:
      - NET_ADMIN
    networks:
      vlan-rrhh:
        ipv4_address: 10.80.20.10

  router-vlan:
    image: lab-host:local
    hostname: router-vlan
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vlan-ventas:
        ipv4_address: 10.80.10.254
      vlan-rrhh:
        ipv4_address: 10.80.20.254

networks:
  vlan-ventas:
    ipam:
      config:
        - subnet: 10.80.10.0/24
  vlan-rrhh:
    ipam:
      config:
        - subnet: 10.80.20.0/24
