services:
  servidor-dhcp:
    image: lab-host:local
    hostname: servidor-dhcp
    cap_add:
      - NET_ADMIN
    command: ["dnsmasq", "-k", "-C", "/etc/dnsmasq.conf"]
    volumes:
      - ./dnsmasq-dhcp.conf:/etc/dnsmasq.conf:ro
    networks:
      lan-dhcp:
        ipv4_address: 192.168.53.254

  cliente-dhcp:
    image: lab-host:local
    hostname: cliente-dhcp
    depends_on:
      - servidor-dhcp
    cap_add:
      - NET_ADMIN
    networks:
      lan-dhcp:

networks:
  lan-dhcp:
    ipam:
      config:
        - subnet: 192.168.53.0/24
